### ISSUE TITLE
Logo Proposal for Reputation

### ISSUE THREAD

**Issue by area55git** [FinalSFE/Reputation#1]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project Reputation.

I will be pleased to collaborate with you.

**Comment by Amine-Project** [comment]
Sorry for the late response. and yes we would be happy to collaborate with you.

**Comment by area55git** [comment]
Perfect..! I am very enthusiastic to design a Logo for your project.
If you have some ideas, suggestions as to style or colors would be great to be able to start.
I also need a brief summary of Reputation to get a better idea.

**Comment by Amine-Project** [comment]
it's an android application where you rate people you know and you can see your rating to know what others think about you.
![capture](https://user-images.githubusercontent.com/23407569/40869426-5ba89df4-660a-11e8-8825-8a297b802882.PNG)
you can use these  colors : #00BCD4 #0097A7 with the white color for the icon

**Comment by area55git** [comment]
Hi, @Amine-Project, are you still interested in the proposal? Today I'm going to start with the sketches.

**Comment by Amine-Project** [comment]
Yes I'm still interested.

**Comment by area55git** [comment]
perfect, tomorrow I send you the proposals

**Comment by area55git** [comment]
Hi @Amine-Project, Do you like this proposal?

[![LOGO_PROPOSAL_FOR_REPUTATION.jpg](https://s33.postimg.cc/eswrmggr3/LOGO_PROPOSAL_FOR_REPUTATION.jpg)](https://postimg.cc/image/9hhv1quob/)

**Comment by Amine-Project** [comment]
Yes it is Nice
I like the icon on the left

**Comment by area55git** [comment]
Perfect, I'll prepare the final files, and make a PR in the readme folder to merge it

**Comment by area55git** [comment]
Hi @Amine-Project in the link are the files in various formats

### [FILE DOWNLOAD](https://drive.google.com/open?id=1_BMiLgw_xZad36MWGZg8Oxs-61HhOPNn)

[![DERECHOS.jpg](https://s33.postimg.cc/otni5j2fz/DERECHOS.jpg)](https://postimg.cc/image/9kxkrr8rf/)
This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

**Comment by area55git** [comment]
PR #2

**Comment by Amine-Project** [comment]
Done

**Comment by area55git** [comment]
Thank you for allowing us to collaborate in your project. I am at your service for the logo design of your next projects

**Comment by Amine-Project** [comment]
It's my honor to collaborate with you bro.
